### ISSUE TITLE
'preview' appears to be broken

### ISSUE THREAD

**Issue by jgravois** [koopjs/koop-github#19]
STR
* clone koop-sample-app
* update package.json to load
```
"dependencies": {
    ...
    "koop": "^2.5.2",
    ...
    "koop-github": "^1.0.0",
```

* install dependencies and start the server
* navigate to http://localhost:1337/github.  the map loads, but an error is thrown to the console.
```
// line 88 of map.js
if (module && module.exports) module.exports = koopMap
// module isn't defined
```

* if you try to preview an actual .geojson file, things **really** get interesting
http://localhost:1337/github/chelm/grunt-geo/forks/preview
```
>> line 63 of views/demo.ejs
koop.add(location.origin + '/github/<%= user %>/<%= repo %>/<%= file %>/FeatureServer/0');
// user isn't defined
```

am i missing something regarding compatibility/dependencies?

**Comment by ngoldman** [comment]
@jgravois line 88 shouldn't be throwing an error as the whole purpose of that line is to only export if module exists... that was a silly workaround for the standard linter.

As for line 63, I feel like I've seen that one before. I'm not sure preview has worked for a while. :(

**Comment by ngoldman** [comment]
Quick check in console leads me to believe I was **doing it wrong** regarding the module thing at least.

I think I should be checking `typeof module !== 'undefined' && module.exports` instead of just `module && module.exports`... I thought that shorthand worked fine but I guess I am remembering that wrong.
